import datetime
from typing import Optional
from sqlalchemy import BigInteger, String, Integer, DateTime, Boolean, DECIMAL, SmallInteger, text, FetchedValue
from sqlalchemy.dialects.mssql import TIMESTAMP
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.schema import ForeignKey
from database.db import Base

class ATM(Base):
    __tablename__ = "ATMs"

    Id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    TerminalId: Mapped[str] = mapped_column(String(50), unique=True, nullable=False)
    ATMCode: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    ATMName: Mapped[str] = mapped_column(String(150), nullable=False)
    BranchCode: Mapped[str] = mapped_column(String(50), nullable=False)
    BranchName: Mapped[str] = mapped_column(String(100), nullable=False)
    Zone: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    IPAddress: Mapped[Optional[str]] = mapped_column(String(45), nullable=True)
    HostName: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    Vendor: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    Model: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    SerialNumber: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    WindowsVersion: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    BiosVersion: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    AgentVersion: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    AgentEnabled: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("1"))
    LastHeartbeat: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime, nullable=True)
    LastAgentStart: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime, nullable=True)
    LastStatus: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    IsActive: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("1"))
    EJLogPath: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    AgentName: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    CreatedOn: Mapped[datetime.datetime] = mapped_column(DateTime, nullable=False, server_default=text("SYSDATETIME()"))
    UpdatedOn: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime, nullable=True)
    RowVersion: Mapped[bytes] = mapped_column(TIMESTAMP, nullable=False, server_default=FetchedValue(), server_onupdate=FetchedValue())

class AgentFileState(Base):
    __tablename__ = "AgentFileState"

    Id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    ATMId: Mapped[int] = mapped_column(BigInteger, ForeignKey("ATMs.Id", ondelete="CASCADE"), nullable=False)
    FilePath: Mapped[str] = mapped_column(String(500), nullable=False)
    FileName: Mapped[str] = mapped_column(String(260), nullable=False)
    LastFileSize: Mapped[Optional[int]] = mapped_column(BigInteger, nullable=True)
    LastReadOffset: Mapped[int] = mapped_column(BigInteger, nullable=False, server_default=text("0"))
    LastModifiedTime: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime, nullable=True)
    LastParsedEventTime: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime, nullable=True)
    LastSequenceNumber: Mapped[Optional[int]] = mapped_column(BigInteger, nullable=True)
    FileHash: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    IsActive: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("1"))
    CreatedOn: Mapped[datetime.datetime] = mapped_column(DateTime, nullable=False, server_default=text("SYSDATETIME()"))
    UpdatedOn: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime, nullable=True)
    RowVersion: Mapped[bytes] = mapped_column(TIMESTAMP, nullable=False, server_default=FetchedValue(), server_onupdate=FetchedValue())

class ATMEvent(Base):
    __tablename__ = "ATMEvents"

    Id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    ATMId: Mapped[int] = mapped_column(BigInteger, ForeignKey("ATMs.Id", ondelete="CASCADE"), nullable=False)
    EventSequenceNumber: Mapped[Optional[int]] = mapped_column(BigInteger, nullable=True)
    EventTime: Mapped[datetime.datetime] = mapped_column(DateTime, nullable=False)
    EventType: Mapped[str] = mapped_column(String(50), nullable=False)
    EventCategory: Mapped[str] = mapped_column(String(50), nullable=False)
    Severity: Mapped[str] = mapped_column(String(20), nullable=False)
    TerminalStatus: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    Message: Mapped[Optional[str]] = mapped_column(String(2000), nullable=True)
    CardNumberMasked: Mapped[Optional[str]] = mapped_column(String(25), nullable=True)
    ResponseCode: Mapped[Optional[str]] = mapped_column(String(10), nullable=True)
    FunctionId: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    Opcode: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    Amount: Mapped[Optional[float]] = mapped_column(DECIMAL(18, 2), nullable=True)
    CassetteNo: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    RemainingNotes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    RejectNotes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    SupervisorMode: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    IsCashAdded: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("0"))
    IsCashRemoved: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("0"))
    IsCassetteInserted: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("0"))
    IsCassetteRemoved: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("0"))
    IsRejectBinRemoved: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("0"))
    IsRejectBinInserted: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("0"))
    IsCardCaptured: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("0"))
    IsTransactionStart: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("0"))
    IsTransactionEnd: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("0"))
    RawEvent: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    SourceFileName: Mapped[Optional[str]] = mapped_column(String(260), nullable=True)
    SourceLineNumber: Mapped[Optional[int]] = mapped_column(BigInteger, nullable=True)
    ParseStatus: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))
    TerminalIdSnapshot: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    CreatedOn: Mapped[datetime.datetime] = mapped_column(DateTime, nullable=False, server_default=text("SYSDATETIME()"))
    RowVersion: Mapped[bytes] = mapped_column(TIMESTAMP, nullable=False, server_default=FetchedValue(), server_onupdate=FetchedValue())

class ATMLiveStatus(Base):
    __tablename__ = "AtmLiveStatus"

    ATMId: Mapped[int] = mapped_column(BigInteger, ForeignKey("ATMs.Id", ondelete="CASCADE"), primary_key=True)
    IsOnline: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("0"))
    CurrentStatus: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    SSTStatus: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    SupervisorMode: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("0"))
    LastHeartbeat: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime, nullable=True)
    LastAgentHeartbeat: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime, nullable=True)
    LastEventType: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    LastEventTime: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime, nullable=True)
    LastTransactionTime: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime, nullable=True)
    LastTransactionAmount: Mapped[Optional[float]] = mapped_column(DECIMAL(18, 2), nullable=True)
    CardReaderStatus: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    RejectBinStatus: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    CashAvailable: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("1"))
    TotalRemainingNotes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    CashRemainingAmount: Mapped[Optional[float]] = mapped_column(DECIMAL(18, 2), nullable=True)
    Cassette1Status: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    Cassette1RemainingNotes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    Cassette2Status: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    Cassette2RemainingNotes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    Cassette3Status: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    Cassette3RemainingNotes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    Cassette4Status: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    Cassette4RemainingNotes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    LastErrorMessage: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    CreatedOn: Mapped[datetime.datetime] = mapped_column(DateTime, nullable=False, server_default=text("SYSDATETIME()"))
    UpdatedOn: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime, nullable=True)
    RowVersion: Mapped[bytes] = mapped_column(TIMESTAMP, nullable=False, server_default=FetchedValue(), server_onupdate=FetchedValue())

class CassetteBalanceHistory(Base):
    __tablename__ = "CassetteBalanceHistory"

    Id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    ATMId: Mapped[int] = mapped_column(BigInteger, ForeignKey("ATMs.Id", ondelete="CASCADE"), nullable=False)
    EventId: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("ATMEvents.Id"), nullable=True)
    EventSequenceNumber: Mapped[Optional[int]] = mapped_column(BigInteger, nullable=True)
    EventTime: Mapped[datetime.datetime] = mapped_column(DateTime, nullable=False)
    CassetteNo: Mapped[int] = mapped_column(Integer, nullable=False)
    CassetteStatus: Mapped[str] = mapped_column(String(30), nullable=False)
    Denomination: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    CurrencyCode: Mapped[Optional[str]] = mapped_column(String(10), nullable=True)
    LoadedNotes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    RemainingNotes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    RejectedNotes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    DispensedNotes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    CashAmount: Mapped[Optional[float]] = mapped_column(DECIMAL(18, 2), nullable=True)
    OperationType: Mapped[str] = mapped_column(String(30), nullable=False)
    SourceFileName: Mapped[Optional[str]] = mapped_column(String(260), nullable=True)
    SourceLineNumber: Mapped[Optional[int]] = mapped_column(BigInteger, nullable=True)
    CreatedOn: Mapped[datetime.datetime] = mapped_column(DateTime, nullable=False, server_default=text("SYSDATETIME()"))
    RowVersion: Mapped[bytes] = mapped_column(TIMESTAMP, nullable=False, server_default=FetchedValue(), server_onupdate=FetchedValue())

class AgentSettings(Base):
    __tablename__ = "AgentSettings"

    Id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    PollingIntervalSeconds: Mapped[int] = mapped_column(SmallInteger, nullable=False, server_default=text("5"))
    HeartbeatIntervalSeconds: Mapped[int] = mapped_column(SmallInteger, nullable=False, server_default=text("30"))
    PingIntervalSeconds: Mapped[int] = mapped_column(SmallInteger, nullable=False, server_default=text("300"))
    LogScanIntervalSeconds: Mapped[int] = mapped_column(SmallInteger, nullable=False, server_default=text("2"))
    OfflineThresholdMinutes: Mapped[int] = mapped_column(SmallInteger, nullable=False, server_default=text("60"))
    CriticalOfflineThresholdMinutes: Mapped[int] = mapped_column(SmallInteger, nullable=False, server_default=text("120"))
    LowCashThresholdAmount: Mapped[float] = mapped_column(DECIMAL(18, 2), nullable=False, server_default=text("500000"))
    EJLogPath: Mapped[str] = mapped_column(String(500), nullable=False)
    RetentionDays: Mapped[int] = mapped_column(SmallInteger, nullable=False, server_default=text("90"))
    MaxLogFileSizeMB: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("100"))
    EnableHeartbeat: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("1"))
    EnablePing: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("1"))
    EnableLogParser: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("1"))
    EnableAutoRecovery: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("0"))
    AgentVersion: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    CreatedOn: Mapped[datetime.datetime] = mapped_column(DateTime, nullable=False, server_default=text("SYSDATETIME()"))
    UpdatedOn: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime, nullable=True)
    RowVersion: Mapped[bytes] = mapped_column(TIMESTAMP, nullable=False, server_default=FetchedValue(), server_onupdate=FetchedValue())

class AgentHealthLog(Base):
    __tablename__ = "AgentHealthLog"

    Id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    ATMId: Mapped[int] = mapped_column(BigInteger, ForeignKey("ATMs.Id", ondelete="CASCADE"), nullable=False)
    LogTime: Mapped[datetime.datetime] = mapped_column(DateTime, nullable=False)
    Level: Mapped[str] = mapped_column(String(20), nullable=False)
    EventType: Mapped[str] = mapped_column(String(50), nullable=False)
    Message: Mapped[Optional[str]] = mapped_column(String(2000), nullable=True)
    ExceptionDetails: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    SourceFileName: Mapped[Optional[str]] = mapped_column(String(260), nullable=True)
    CreatedOn: Mapped[datetime.datetime] = mapped_column(DateTime, nullable=False, server_default=text("SYSDATETIME()"))
    RowVersion: Mapped[bytes] = mapped_column(TIMESTAMP, nullable=False, server_default=FetchedValue(), server_onupdate=FetchedValue())
